### ISSUE TITLE
Conversión bidireccional

### ISSUE THREAD

**Issue by ghost** [humanytek-team/raloy_product_viscosity2#2]
Al parece la conversión bidireccional no está funcionando.

**Comment by AfroMonkey** [comment]
> Al parece la conversión bidireccional no está funcionando.

En qué parte?

**Comment by ghost** [comment]
Cuando estás haciendo la orden de compra, si modificas la cantidad del proveedor, al salir del campo no actualiza la cantidad local o viceversa.
